# Generated by Django 4.1.7 on 2023-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodHands', '0003_alter_institution_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
